--INSERT INTO catalog(product_id, product_name, stock, unit_price)
--values ('CATALOG-001', 'Berling', 100, 1500)
--INSERT INTO catalog(product_id, product_name, stock, unit_price)
--values ('CATALOG-002', 'Aerling', 23, 1100)