server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC&characterEncoding=UTF-8
    username: hoonki
    password: as789456
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Hello world

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    com.example.userservice.client: DEBUG